{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.5.1.jar",
          "url": "room-compiler-processing-2.5.1.jar",
          "size": 1040503,
          "sha512": "5fb772857be9920706225e2f0e10a7b4dad9d748400745581b3f1cfa5ff5f6cad9ca71d47db78b511d510c4281505e6ff38ea3a6fc6bbc54573cdbd654a5e910",
          "sha256": "192fbb532266bf13e4ddaa0c9af0a03915f865445e450eb3c561bae53561c3dd",
          "sha1": "0256720d03092f60bfa287dc617577ad4412eee2",
          "md5": "a6312b99644f34e52e1dff42f44a3bcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.7.20-1.0.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.5.1.jar",
          "url": "room-compiler-processing-2.5.1.jar",
          "size": 1040503,
          "sha512": "5fb772857be9920706225e2f0e10a7b4dad9d748400745581b3f1cfa5ff5f6cad9ca71d47db78b511d510c4281505e6ff38ea3a6fc6bbc54573cdbd654a5e910",
          "sha256": "192fbb532266bf13e4ddaa0c9af0a03915f865445e450eb3c561bae53561c3dd",
          "sha1": "0256720d03092f60bfa287dc617577ad4412eee2",
          "md5": "a6312b99644f34e52e1dff42f44a3bcd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.5.1-sources.jar",
          "url": "room-compiler-processing-2.5.1-sources.jar",
          "size": 223560,
          "sha512": "29f4afbcdf974e630029c33c0b8d7b36d680464d5caa4be2407dde4145d8d2b9b0aba1a9fac1571a10cffe9d7a4bd4af4c8a5c09adac19cd3807b7bf2723691f",
          "sha256": "42c371604065321d24b3fde4a62893e7fddf0882ce2790e2e4f06144faff10c8",
          "sha1": "51480a3287dc45fbb21b8e511c3438c031805fdd",
          "md5": "7d4680e2e537c29dcf20516de1b2b8bf"
        }
      ]
    }
  ]
}