{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0.aar",
          "url": "lifecycle-service-2.4.0.aar",
          "size": 4300,
          "sha512": "3f803703b65575fd0f595ab3339e32af77d854f50774dc48c8b9cfba9cc0d6b0b106c38446652c0206f982764039b51a8926fb806fbf852a900bbdd7ffeb397f",
          "sha256": "9c8de74eed399fe2a0e80bea2a58d6d1327e371f77ac7484c99beb4d84491db8",
          "sha1": "ef714613b3fe879349314f7d58f48a06531c98e4",
          "md5": "0a7ebbb7bfbd427ac0575aa566e6cdbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0.aar",
          "url": "lifecycle-service-2.4.0.aar",
          "size": 4300,
          "sha512": "3f803703b65575fd0f595ab3339e32af77d854f50774dc48c8b9cfba9cc0d6b0b106c38446652c0206f982764039b51a8926fb806fbf852a900bbdd7ffeb397f",
          "sha256": "9c8de74eed399fe2a0e80bea2a58d6d1327e371f77ac7484c99beb4d84491db8",
          "sha1": "ef714613b3fe879349314f7d58f48a06531c98e4",
          "md5": "0a7ebbb7bfbd427ac0575aa566e6cdbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.0-sources.jar",
          "url": "lifecycle-service-2.4.0-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
