{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0.aar",
          "url": "lifecycle-livedata-core-2.4.0.aar",
          "size": 9446,
          "sha512": "cb3737acec9d120c201d1ac4c27084813d8a28b1a0ae45d0c75f3e59c41a658a09b8cb572f54f19396bd44c992580494d180922ae7234936cc577e440d365bef",
          "sha256": "6f25e357320ec341e440e02d08f6ff54ae99a367c9106e864e6e8df3df5cdafc",
          "sha1": "229c4970d9fc4016b1b605a489732de57fd041d2",
          "md5": "4dbcaec57cdd33b8c9cecba63fbc487d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0.aar",
          "url": "lifecycle-livedata-core-2.4.0.aar",
          "size": 9446,
          "sha512": "cb3737acec9d120c201d1ac4c27084813d8a28b1a0ae45d0c75f3e59c41a658a09b8cb572f54f19396bd44c992580494d180922ae7234936cc577e440d365bef",
          "sha256": "6f25e357320ec341e440e02d08f6ff54ae99a367c9106e864e6e8df3df5cdafc",
          "sha1": "229c4970d9fc4016b1b605a489732de57fd041d2",
          "md5": "4dbcaec57cdd33b8c9cecba63fbc487d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-sources.jar",
          "url": "lifecycle-livedata-core-2.4.0-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
